server:
  port: 8000

spring:
  application:
    name: fintest
  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:/db/db.changelog-master.yaml
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/fintest_db}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver